
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

/**
 * Same problem as src/lib/prisma.ts: the connection string doesn't always
 * arrive under the name we expect, because Vercel's Neon integration prefixes
 * the variables it creates. `env()` from prisma/config throws when the one
 * name it's given is missing — which fails the build during `migrate deploy` —
 * so resolve it ourselves instead.
 *
 * Migrations need a direct (non-pooled) connection either way: Neon's pooled
 * URL goes through PgBouncer, which doesn't support the session-level advisory
 * lock `prisma migrate deploy` takes, and times out with error P1002.
 *
 * The list is duplicated rather than imported because the Prisma CLI loads
 * this file on its own, outside the app's module graph.
 */
function connectionString(): string {
  const names = [
    "DIRECT_URL",
    "DATABASE_URL_UNPOOLED",
    "DATABASE_DATABASE_URL_UNPOOLED",
    "POSTGRES_URL_NON_POOLING",
    "DATABASE_POSTGRES_URL_NON_POOLING",
    "DATABASE_URL",
  ];
  for (const name of names) {
    const value = process.env[name];
    if (value) return value;
  }
  throw new Error(
    `No database connection string found. Set one of: ${names.join(", ")}.`
  );
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    url: connectionString(),
    directUrl: connectionString(),
  },
});
