
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    // DATABASE_URL (pooled, via PgBouncer) was unreachable at runtime;
    // DATABASE_URL_UNPOOLED is confirmed working — see prisma/schema.prisma.
    url: env("DATABASE_URL_UNPOOLED"),
    directUrl: env("DIRECT_URL"),
  },
});
